### ISSUE TITLE
request_test.go:42-42: Verify Id, Timeout and Content

### ISSUE THREAD

**Issue by 0pdd** [fxnn/deadbox#1]
The puzzle `2-0082b70e` (from #2) in [`it/request_test.go`](https://github.com/fxnn/deadbox/blob/master/it/request_test.go) (lines 42-42) has to be resolved: "Verify Id, Timeout and Content"

The puzzle was created by Felix Neumann on 26-Aug-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by fxnn** [comment]
Duplicate -> closed
