### ISSUE TITLE
facade.go:85-85: drop must accept responses

### ISSUE THREAD

**Issue by 0pdd** [fxnn/deadbox#10]
The puzzle `5-d794d29b` (from #5) in [`drop/facade.go`](https://github.com/fxnn/deadbox/blob/master/drop/facade.go) (lines 85-85) has to be resolved: "drop must accept responses"

The puzzle was created by Felix Neumann on 26-Aug-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by fxnn** [comment]
Duplicate -> closed
