### ISSUE TITLE
processor.go:27-27: never process a request twice

### ISSUE THREAD

**Issue by 0pdd** [fxnn/deadbox#11]
The puzzle `7-2980fcfe` (from #7) in [`worker/processor.go`](https://github.com/fxnn/deadbox/blob/master/worker/processor.go) (lines 27-27) has to be resolved: "never process a request twice"

The puzzle was created by Felix Neumann on 27-Aug-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by fxnn** [comment]
Duplicate -> closed
