### ISSUE TITLE
processor.go:52-52: create a queue of items to process...

### ISSUE THREAD

**Issue by 0pdd** [fxnn/deadbox#12]
The puzzle `7-3351e7e7` (from #7) in [`worker/processor.go`](https://github.com/fxnn/deadbox/blob/master/worker/processor.go) (lines 52-52) has to be resolved: "create a queue of items to process and process them"

The puzzle was created by Felix Neumann on 27-Aug-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by fxnn** [comment]
Duplicate -> closed
