### ISSUE TITLE
requests.go:42-42: decrypt requests

### ISSUE THREAD

**Issue by 0pdd** [fxnn/deadbox#23]
The puzzle `7-633161db` (from #7) in [`worker/requests.go`](https://github.com/fxnn/deadbox/blob/master/worker/requests.go) (lines 42-42) has to be resolved: "decrypt requests"

The puzzle was created by Felix Neumann on 16-Sep-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by fxnn** [comment]
Precondition: encryption, esp. #25

**Comment by 0pdd** [comment]
The puzzle `7-633161db` has disappeared from the source code, that's why I closed this issue.
