### ISSUE TITLE
daemon.go:32-32: Make Start()/Stop() thread safe

### ISSUE THREAD

**Issue by 0pdd** [fxnn/deadbox#4]
The puzzle `1-0d74c8e7` (from #1) in [`daemon/daemon.go`](https://github.com/fxnn/deadbox/blob/master/daemon/daemon.go) (lines 32-32) has to be resolved: "Make Start()/Stop() thread safe"

The puzzle was created by Felix Neumann on 26-Aug-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by fxnn** [comment]
Duplicate -> closed
