### ISSUE TITLE
deadbox.go:23-23: replace dummy config with...

### ISSUE THREAD

**Issue by 0pdd** [fxnn/deadbox#5]
The puzzle `4-3f50223d` (from #4) in [`cmd/deadbox.go`](https://github.com/fxnn/deadbox/blob/master/cmd/deadbox.go) (lines 23-23) has to be resolved: "replace dummy config with configuration mechanism"

The puzzle was created by Felix Neumann on 26-Aug-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by fxnn** [comment]
Duplicate -> closed
